import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

#env.Program(os.path.join(BIN_DIR, 'awtkRun'), ['main.c', 'awtk_lua.c', Glob('assets*.c')])

env.SharedLibrary(os.path.join(BIN_DIR, 'openawtk'), ['awtk_lua.c'])


